// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: project_02

#include "../ui.h"

lv_obj_t *ui_MainScreen;
lv_obj_t *ui_TabView2;
lv_obj_t *ui_TabPage1;
lv_obj_t *ui_Chart2;
lv_obj_t *ui_Chart2_Xaxis;
lv_obj_t *ui_Chart2_Yaxis1;
lv_obj_t *ui_Chart2_Yaxis2;
lv_obj_t *ui_TabPage2;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_TabPage3;
lv_obj_t *ui_Keyboard2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Calendar1;
lv_obj_t *ui_Spinner2;

// event funtions
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      background_color_clicked( e );
}
}

// build funtions

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_add_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_set_scroll_dir(ui_MainScreen, LV_DIR_HOR);
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x671111), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView2 = lv_tabview_create(ui_MainScreen);
lv_tabview_set_tab_bar_size(ui_TabView2,25);
lv_obj_set_width( ui_TabView2, 294);
lv_obj_set_height( ui_TabView2, 173);
lv_obj_set_x( ui_TabView2, -1 );
lv_obj_set_y( ui_TabView2, 14 );
lv_obj_set_align( ui_TabView2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TabView2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabPage1 = lv_tabview_add_tab(ui_TabView2, "Main");

ui_Chart2 = lv_chart_create(ui_TabPage1);
lv_obj_set_width( ui_Chart2, 200);
lv_obj_set_height( ui_Chart2, 100);
lv_obj_set_x( ui_Chart2, 0 );
lv_obj_set_y( ui_Chart2, -11 );
lv_obj_set_align( ui_Chart2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_Chart2, LV_CHART_TYPE_LINE);

ui_Chart2_Xaxis = lv_scale_create( ui_Chart2 );
lv_scale_set_mode( ui_Chart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_Chart2_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_Chart2_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_Chart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_Chart2_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart2_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_Chart2_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart2_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_Chart2_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_Chart2_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_Chart2_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart2_Xaxis, 2 >= 1 ? 2 : 1 );
ui_Chart2_Yaxis1 = lv_scale_create( ui_Chart2 );
lv_scale_set_mode( ui_Chart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_Chart2_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_Chart2_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_Chart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart2,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart2,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_Chart2_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart2_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart2_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart2_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart2_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart2_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart2_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_Chart2_Yaxis2 = lv_scale_create( ui_Chart2 );
lv_scale_set_mode( ui_Chart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_Chart2_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_Chart2_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_Chart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_Chart2_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart2_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart2_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart2_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart2_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart2_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart2_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart2_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_Chart2, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_Chart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "Debug");

ui_Button1 = lv_button_create(ui_TabPage2);
lv_obj_set_width( ui_Button1, 216);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, -5 );
lv_obj_set_y( ui_Button1, -1 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -5 );
lv_obj_set_y( ui_Label2, -1 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Change Background Color");

ui_TabPage3 = lv_tabview_add_tab(ui_TabView2, "Log");

ui_Keyboard2 = lv_keyboard_create(ui_TabPage3);
lv_obj_set_width( ui_Keyboard2, 236);
lv_obj_set_height( ui_Keyboard2, 92);
lv_obj_set_x( ui_Keyboard2, 0 );
lv_obj_set_y( ui_Keyboard2, 13 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );

ui_Label1 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -12 );
lv_obj_set_y( ui_Label1, -98 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"<< Slide for additional content >>");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x3AFE0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calendar1 = lv_calendar_create(ui_MainScreen);
lv_obj_t *ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
lv_obj_set_width( ui_Calendar1, 230);
lv_obj_set_height( ui_Calendar1, 181);
lv_obj_set_x( ui_Calendar1, 291 );
lv_obj_set_y( ui_Calendar1, 8 );
lv_obj_set_align( ui_Calendar1, LV_ALIGN_CENTER );

ui_Spinner2 = lv_spinner_create(ui_MainScreen);
//lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
lv_obj_set_width( ui_Spinner2, 80);
lv_obj_set_height( ui_Spinner2, 80);
lv_obj_set_x( ui_Spinner2, 482 );
lv_obj_set_y( ui_Spinner2, -4 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
   if (ui_MainScreen) lv_obj_del(ui_MainScreen);

// NULL screen variables
ui_MainScreen= NULL;
ui_TabView2= NULL;
ui_TabPage1= NULL;
ui_Chart2= NULL;
ui_TabPage2= NULL;
ui_Button1= NULL;
ui_Label2= NULL;
ui_TabPage3= NULL;
ui_Keyboard2= NULL;
ui_Label1= NULL;
ui_Calendar1= NULL;
ui_Spinner2= NULL;

}
