// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: project_02

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_TabView2;
extern lv_obj_t *ui_TabPage1;
extern lv_obj_t *ui_Chart2;
extern lv_obj_t *ui_Chart2_Xaxis;
extern lv_obj_t *ui_Chart2_Yaxis1;
extern lv_obj_t *ui_Chart2_Yaxis2;
extern lv_obj_t *ui_TabPage2;
extern void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_TabPage3;
extern lv_obj_t *ui_Keyboard2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Calendar1;
extern lv_obj_t *ui_Spinner2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

