// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: SquareLine_BME680_Project

#ifndef UI_BME680SCREEN_H
#define UI_BME680SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BME680Screen
extern void ui_BME680Screen_screen_init(void);
extern void ui_BME680Screen_screen_destroy(void);
extern lv_obj_t *ui_BME680Screen;
extern lv_obj_t *ui_TopContainer;
extern lv_obj_t *ui_TempContainer;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_FDegLabel;
extern lv_obj_t *ui_TempDescLabel;
extern lv_obj_t *ui_HumidContainer;
extern lv_obj_t *ui_HumidArc;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_HumDescLabel;
extern lv_obj_t *ui_BottomContainer;
extern lv_obj_t *ui_PressureContainer;
extern lv_obj_t *ui_PressLabel;
extern lv_obj_t *ui_PressureChart;
extern lv_obj_t *ui_PressureChart_Xaxis;
extern lv_obj_t *ui_PressureChart_Yaxis1;
extern lv_obj_t *ui_PressureChart_Yaxis2;
extern lv_obj_t *ui_AirResContainer;
extern lv_obj_t *ui_AirResDescLabel;
extern lv_obj_t *ui_AirResistanceOutputLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

