// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: SquareLine_BME680_Project

#include "../ui.h"

lv_obj_t *ui_Screen1;
lv_obj_t *ui_Container1;
lv_obj_t *ui_Arc1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_HumidArc;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label6;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 320);
lv_obj_set_height( ui_Container1, 240);
lv_obj_set_x( ui_Container1, -1 );
lv_obj_set_y( ui_Container1, -1 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_Container1);
lv_obj_set_width( ui_Arc1, 120);
lv_obj_set_height( ui_Arc1, 120);
lv_obj_set_x( ui_Arc1, -74 );
lv_obj_set_y( ui_Arc1, -50 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Arc1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Arc1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_arc_set_value(ui_Arc1, 50);
lv_obj_set_style_pad_left(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x3C08FA), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Arc1, lv_color_hex(0xEB1212), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Arc1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Arc1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFC0540), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_Arc1, lv_color_hex(0xF90F0F), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Arc1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Arc1, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Arc1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 72 );
lv_obj_set_y( ui_Label1, 48 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Label1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Label1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Label1,"--.-°C");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HumidArc = lv_arc_create(ui_Container1);
lv_obj_set_width( ui_HumidArc, 120);
lv_obj_set_height( ui_HumidArc, 120);
lv_obj_set_x( ui_HumidArc, 70 );
lv_obj_set_y( ui_HumidArc, -50 );
lv_obj_set_align( ui_HumidArc, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HumidArc,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HumidArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_arc_set_value(ui_HumidArc, 50);
lv_obj_set_style_pad_left(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_HumidArc, lv_color_hex(0x666669), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_HumidArc, lv_color_hex(0x05058F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_HumidArc);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"--.-%");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 59 );
lv_obj_set_y( ui_Label5, -77 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Humidity");

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -58 );
lv_obj_set_y( ui_Label6, -76 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Tempurature");

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Container1= NULL;
ui_Arc1= NULL;
ui_Label1= NULL;
ui_HumidArc= NULL;
ui_Label2= NULL;
ui_Label5= NULL;
ui_Label6= NULL;

}
