// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: PWM_Slider

#include "ui.h"
#include "main.h"
#include <stdio.h>
#include "lvgl.h"

extern TIM_HandleTypeDef htim2;

static char buf[4];

void slider_changed(lv_event_t * e)
{
	int value = lv_slider_get_value(lv_event_get_target(e));
	sprintf(buf, "Slider Value: %d", value);

	lv_textarea_set_text(ui_TextArea1, buf);
	if (value < 0) {
		value = 0;
	} else if (value > 100) {
		value = 100;
	}
	TIM2->CCR1 = value;

}

