// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: PWM_Slider

#include "ui.h"
#include "main.h"
#include <stdio.h>
#include "lvgl.h"

extern TIM_HandleTypeDef htim2;

static char buf[4];

#define PWM_FREQUENCY 40000

void slider_changed(lv_event_t * e)
{
	int value = lv_slider_get_value(lv_event_get_target(e));
	sprintf(buf, "Slider Value: %d", value);

	lv_textarea_set_text(ui_TextArea1, buf);

	// validate the value
	if (value < 0 || value > 100) {
		lv_textarea_set_text(ui_TextArea1, "Invalid Value");
		lv_slider_set_value(lv_event_get_target(e), 0); // Reset slider to 0
		return;
	}
	
	// calculate the duty cycle for inserting into the CCR
	uint32_t ccr_value = (uint32_t)((value / 100.0) * (HAL_RCC_GetPCLK1Freq() / PWM_FREQUENCY));
	// set the PWM duty cycle
	__HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, ccr_value);
	// update the text area with the new value
	sprintf(buf, "%d", ccr_value);
	lv_textarea_set_text(ui_TextArea2, buf);

}

