// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: SquareLine_BME680_Project

#include "../ui.h"

lv_obj_t *ui_BME680Screen;
lv_obj_t *ui_TopContainer;
lv_obj_t *ui_TempContainer;
lv_obj_t *ui_Arc1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_FDegLabel;
lv_obj_t *ui_TempDescLabel;
lv_obj_t *ui_HumidContainer;
lv_obj_t *ui_HumidArc;
lv_obj_t *ui_Label2;
lv_obj_t *ui_HumDescLabel;
lv_obj_t *ui_BottomContainer;
lv_obj_t *ui_PressureContainer;
lv_obj_t *ui_PressLabel;
lv_obj_t *ui_PressureChart;
lv_obj_t *ui_PressureChart_Xaxis;
lv_obj_t *ui_PressureChart_Yaxis1;
lv_obj_t *ui_PressureChart_Yaxis2;
lv_obj_t *ui_AirResContainer;
lv_obj_t *ui_AirResDescLabel;
lv_obj_t *ui_AirResistanceOutputLabel;

// event funtions

// build funtions

void ui_BME680Screen_screen_init(void)
{
ui_BME680Screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_BME680Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_BME680Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_BME680Screen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_BME680Screen, lv_color_hex(0x4A4848), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BME680Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TopContainer = lv_obj_create(ui_BME680Screen);
lv_obj_remove_style_all(ui_TopContainer);
lv_obj_set_width( ui_TopContainer, 320);
lv_obj_set_height( ui_TopContainer, 120);
lv_obj_set_x( ui_TopContainer, -1 );
lv_obj_set_y( ui_TopContainer, -59 );
lv_obj_set_align( ui_TopContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TopContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TopContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_TopContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempContainer = lv_obj_create(ui_TopContainer);
lv_obj_remove_style_all(ui_TempContainer);
lv_obj_set_width( ui_TempContainer, 120);
lv_obj_set_height( ui_TempContainer, 120);
lv_obj_set_align( ui_TempContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TempContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_TempContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_TempContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_TempContainer);
lv_obj_set_width( ui_Arc1, 120);
lv_obj_set_height( ui_Arc1, 120);
lv_obj_set_x( ui_Arc1, -74 );
lv_obj_set_y( ui_Arc1, -50 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Arc1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Arc1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_arc_set_value(ui_Arc1, 50);
lv_obj_set_style_pad_left(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x3C08FA), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Arc1, lv_color_hex(0xEB1212), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Arc1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Arc1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFC0540), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_grad_color(ui_Arc1, lv_color_hex(0xF90F0F), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Arc1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Arc1, LV_GRAD_DIR_HOR, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Arc1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 72 );
lv_obj_set_y( ui_Label1, 48 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Label1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Label1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_Label1,"--.-°C");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FDegLabel = lv_label_create(ui_Arc1);
lv_obj_set_width( ui_FDegLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FDegLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_FDegLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_FDegLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_FDegLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_FDegLabel,"--.-°F");

ui_TempDescLabel = lv_label_create(ui_Arc1);
lv_obj_set_width( ui_TempDescLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempDescLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempDescLabel, 930 );
lv_obj_set_y( ui_TempDescLabel, -577 );
lv_obj_set_align( ui_TempDescLabel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_TempDescLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TempDescLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_TempDescLabel,"Tempurature");
lv_obj_set_style_pad_left(ui_TempDescLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TempDescLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TempDescLabel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TempDescLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HumidContainer = lv_obj_create(ui_TopContainer);
lv_obj_remove_style_all(ui_HumidContainer);
lv_obj_set_width( ui_HumidContainer, 120);
lv_obj_set_height( ui_HumidContainer, 120);
lv_obj_set_align( ui_HumidContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HumidContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HumidContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_HumidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HumidArc = lv_arc_create(ui_HumidContainer);
lv_obj_set_width( ui_HumidArc, 120);
lv_obj_set_height( ui_HumidArc, 120);
lv_obj_set_x( ui_HumidArc, 70 );
lv_obj_set_y( ui_HumidArc, -50 );
lv_obj_set_align( ui_HumidArc, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HumidArc,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HumidArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_arc_set_value(ui_HumidArc, 50);
lv_obj_set_style_pad_left(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HumidArc, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_HumidArc, lv_color_hex(0x666669), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_HumidArc, lv_color_hex(0x05058F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_HumidArc);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"--.-%");

ui_HumDescLabel = lv_label_create(ui_HumidArc);
lv_obj_set_width( ui_HumDescLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HumDescLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HumDescLabel, 171 );
lv_obj_set_y( ui_HumDescLabel, -113 );
lv_obj_set_align( ui_HumDescLabel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_HumDescLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HumDescLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_HumDescLabel,"Humidity");
lv_obj_set_style_pad_left(ui_HumDescLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HumDescLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HumDescLabel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HumDescLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BottomContainer = lv_obj_create(ui_BME680Screen);
lv_obj_remove_style_all(ui_BottomContainer);
lv_obj_set_width( ui_BottomContainer, 320);
lv_obj_set_height( ui_BottomContainer, 120);
lv_obj_set_x( ui_BottomContainer, 7 );
lv_obj_set_y( ui_BottomContainer, -4 );
lv_obj_set_align( ui_BottomContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_BottomContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_BottomContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_BottomContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PressureContainer = lv_obj_create(ui_BottomContainer);
lv_obj_remove_style_all(ui_PressureContainer);
lv_obj_set_width( ui_PressureContainer, 220);
lv_obj_set_height( ui_PressureContainer, 120);
lv_obj_set_align( ui_PressureContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PressureContainer,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_PressureContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_PressureContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_PressureContainer, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PressLabel = lv_label_create(ui_PressureContainer);
lv_obj_set_width( ui_PressLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PressLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PressLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_PressLabel,"----.- hPa");
lv_obj_set_style_text_font(ui_PressLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PressureChart = lv_chart_create(ui_PressureContainer);
lv_obj_set_width( ui_PressureChart, 150);
lv_obj_set_height( ui_PressureChart, 80);
lv_obj_set_align( ui_PressureChart, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_PressureChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_PressureChart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_PressureChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_PressureChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_PressureChart, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_PressureChart, 20);
lv_chart_set_range( ui_PressureChart, LV_CHART_AXIS_PRIMARY_Y, 950, 1050);
lv_chart_set_div_line_count( ui_PressureChart, 3, 3);

ui_PressureChart_Xaxis = lv_scale_create( ui_PressureChart );
lv_scale_set_mode( ui_PressureChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_PressureChart_Xaxis, lv_pct(100), 20 );
lv_obj_set_align( ui_PressureChart_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_PressureChart_Xaxis, 20 + lv_obj_get_style_pad_bottom(ui_PressureChart,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PressureChart,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_PressureChart_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_PressureChart_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_PressureChart_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_PressureChart_Xaxis, 2, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_PressureChart_Xaxis, 5, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_PressureChart_Xaxis, 0, 10 > 0 ? 10 - 1 : 0 );
lv_scale_set_total_tick_count( ui_PressureChart_Xaxis, (10>0 ? 10-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_PressureChart_Xaxis, 2 >= 1 ? 2 : 1 );
ui_PressureChart_Yaxis1 = lv_scale_create( ui_PressureChart );
lv_scale_set_mode( ui_PressureChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_PressureChart_Yaxis1, 20, lv_pct(100) );
lv_obj_set_align( ui_PressureChart_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_PressureChart_Yaxis1, -20 - lv_obj_get_style_pad_left(ui_PressureChart,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_PressureChart,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_PressureChart_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_PressureChart_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_PressureChart_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_PressureChart_Yaxis1, 1, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_PressureChart_Yaxis1, 2, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_PressureChart_Yaxis1,  950, 1050 );
lv_scale_set_total_tick_count( ui_PressureChart_Yaxis1, (3 > 0 ? 3-1 : 0) * 5 + 1 );
lv_scale_set_major_tick_every( ui_PressureChart_Yaxis1, 5 >= 1 ? 5 : 1 );
ui_PressureChart_Yaxis2 = lv_scale_create( ui_PressureChart );
lv_scale_set_mode( ui_PressureChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_PressureChart_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_PressureChart_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_PressureChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_PressureChart,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PressureChart,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_PressureChart_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_PressureChart_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_PressureChart_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_PressureChart_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_PressureChart_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_PressureChart_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_PressureChart_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_scale_set_label_show( ui_PressureChart_Yaxis2, false );
lv_chart_series_t* ui_PressureChart_series_1 = lv_chart_add_series(ui_PressureChart, lv_color_hex(0x04F625), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_PressureChart_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_PressureChart, ui_PressureChart_series_1, ui_PressureChart_series_1_array);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_PressureChart, LV_MAX3(20, 20, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_PressureChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_AirResContainer = lv_obj_create(ui_BottomContainer);
lv_obj_remove_style_all(ui_AirResContainer);
lv_obj_set_width( ui_AirResContainer, 100);
lv_obj_set_height( ui_AirResContainer, 120);
lv_obj_set_align( ui_AirResContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_AirResContainer,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_AirResContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_AirResContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AirResDescLabel = lv_label_create(ui_AirResContainer);
lv_obj_set_width( ui_AirResDescLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AirResDescLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AirResDescLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_AirResDescLabel,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_AirResDescLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_AirResDescLabel,"       Air \nResistance\n\n");
lv_obj_set_style_text_font(ui_AirResDescLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AirResistanceOutputLabel = lv_label_create(ui_AirResContainer);
lv_obj_set_width( ui_AirResistanceOutputLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AirResistanceOutputLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AirResistanceOutputLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AirResistanceOutputLabel,"--- kΩ");

}

void ui_BME680Screen_screen_destroy(void)
{
   if (ui_BME680Screen) lv_obj_del(ui_BME680Screen);

// NULL screen variables
ui_BME680Screen= NULL;
ui_TopContainer= NULL;
ui_TempContainer= NULL;
ui_Arc1= NULL;
ui_Label1= NULL;
ui_FDegLabel= NULL;
ui_TempDescLabel= NULL;
ui_HumidContainer= NULL;
ui_HumidArc= NULL;
ui_Label2= NULL;
ui_HumDescLabel= NULL;
ui_BottomContainer= NULL;
ui_PressureContainer= NULL;
ui_PressLabel= NULL;
ui_PressureChart= NULL;
ui_AirResContainer= NULL;
ui_AirResDescLabel= NULL;
ui_AirResistanceOutputLabel= NULL;

}
